source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby                      '2.6.3'
gem 'rails',              '6.1.3.2'
gem 'puma',               '5.3.2'
gem 'bootsnap',           '1.7.5'
gem 'devise',             '4.8.0'
gem 'devise_token_auth',  '1.1.5'
gem 'rack-cors',          '1.1.1'
gem 'devise-i18n',        '1.9.4'
gem 'mysql2',             '0.5.3'
gem 'carrierwave',        '2.2.2'
gem 'fog-aws',            '3.10.0'

group :development do
  gem 'listen',           '3.5.1'
  gem 'spring',           '2.1.1'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]